Move CI from Travis to Microsoft Azure
part 3: add deployment mechanism

diff --git a/.azure-pipelines/azure-pipelines.yml b/.azure-pipelines/azure-pipelines.yml
--- a/.azure-pipelines/azure-pipelines.yml
+++ b/.azure-pipelines/azure-pipelines.yml
@@ -1,11 +1,3 @@
-trigger:
-  branches:
-    include:
-    - '*'
-  tags:
-    include:
-    - '*'
-
 stages:
 - stage: static
   displayName: Static Analysis
@@ -47,16 +39,25 @@ stages:
           echo BUILD_REPOSITORY_NAME = $(constants.BUILD_REPOSITORY_NAME)
           echo BUILD_SOURCEBRANCH = $(constants.BUILD_SOURCEBRANCH)
           echo AUTOMATED_COMMIT = $(constants.AUTOMATED_COMMIT)
+
+          if [ "$(constants.BUILD_REPOSITORY_NAME)" == "dials/data" ] && \
+             [ "$(constants.AUTOMATED_COMMIT)" == "true" ] && \
+             [[ "$(constants.BUILD_SOURCEBRANCH)" == refs/pull/* ]]; then
+            echo "##[error]Intentionally marking the initial commit of the automated pull request as failed."
+            echo "The pull request requires a second, meaningful commit, which will run normally."
+            exit 1
+          fi
         displayName: Verify constants
 
 - stage: build
   displayName: Build
   dependsOn:
   - static
-  condition: not(and(eq(dependencies.static.outputs['checks.constants.AUTOMATED_COMMIT'], 'true'),
-                     or(startsWith(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/pull/'),
+  condition: and(succeeded(),
+                 not(or(and(eq(dependencies.static.outputs['checks.constants.AUTOMATED_COMMIT'], 'true'),
+                            startsWith(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/pull/')),
                         startsWith(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/heads/update-'))))
-             # Skip entire build step on pointless pull request builds
+             # Skip entire build step on pointless pull request and hash update builds
   jobs:
   - job: build
     displayName: build package
@@ -91,7 +92,9 @@ stages:
           pathToPublish: dist/
           artifactName: package
 
-      - bash: python setup.py checkdocs
+      - bash: |
+          twine check dist/pypi/*
+          python setup.py checkdocs
         displayName: Check package description
 
 - stage: update
@@ -99,7 +102,7 @@ stages:
   dependsOn:
   - static
   condition: and(succeeded(),
-                 eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'Anthchirp/data'),
+                 eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'dials/data'),
                  startsWith(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/heads/update-'),
                  eq(dependencies.static.outputs['checks.constants.AUTOMATED_COMMIT'], 'true'))
              # Only run this stage on automated commits on 'update-...' branches on the main repository
@@ -134,7 +137,7 @@ stages:
   - static
   - build
   condition: and(succeeded(),
-                 not(and(eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'Anthchirp/data'),
+                 not(and(eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'dials/data'),
                          startsWith(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/heads/update-'))))
              # Do not need to bother running tests on automated 'update-...' branches
   jobs:
@@ -154,6 +157,49 @@ stages:
     steps:
     - template: ci.yml
 
+- stage: deploy
+  displayName: Publish release
+  dependsOn:
+  - static
+  - tests
+  condition: and(succeeded(),
+                 eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'dials/data'),
+                 eq(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/heads/master'))
+  jobs:
+  - job: pypi
+    displayName: Publish pypi release
+    pool:
+      vmImage: ubuntu-20.04
+    steps:
+      - checkout: none
+
+      - task: UsePythonVersion@0
+        displayName: Set up python
+        inputs:
+          versionSpec: 3.8
+
+      - task: DownloadBuildArtifacts@0
+        displayName: Get pre-built package
+        inputs:
+          buildType: 'current'
+          downloadType: 'single'
+          artifactName: 'package'
+          downloadPath: '$(System.ArtifactsDirectory)'
+
+      - script: |
+          pip install -U pip
+          pip install twine
+        displayName: Install twine
+
+      - task: TwineAuthenticate@1
+        displayName: Set up credentials
+        inputs:
+          pythonUploadServiceConnection: pypi-dials-data
+
+      - bash: |
+          python -m twine upload -r pypi-dials-data --config-file $(PYPIRC_PATH) $(System.ArtifactsDirectory)/package/pypi/*.tar.gz $(System.ArtifactsDirectory)/package/pypi/*.whl
+        displayName: Publish package
+
 - stage: hashinfo
   displayName: Check missing hashes
   dependsOn:
@@ -162,7 +208,7 @@ stages:
   - tests
   condition: and(succeeded(),
                  eq(dependencies.static.outputs['checks.constants.BUILD_SOURCEBRANCH'], 'refs/heads/master'),
-                 eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'Anthchirp/data'))
+                 eq(dependencies.static.outputs['checks.constants.BUILD_REPOSITORY_NAME'], 'dials/data'))
              # only run this job in the main branch of the main repository
   jobs:
   - job: hashinfo
