Move CI from Travis to Microsoft Azure
part 2 - partial updating logic

diff --git a/.azure-pipelines/update-hashinfo b/.azure-pipelines/update-hashinfo
--- a/.azure-pipelines/update-hashinfo
+++ b/.azure-pipelines/update-hashinfo
@@ -1,78 +1,45 @@
-#!/bin/bash -eux
+#!/bin/bash -eu
 
+echo "##[section]Setting up git configuration"
 git config --global user.name "Azure on github.com/dials/data"
 git config --global user.email "dials@noreply.github.com"
 git config credential.helper "store --file=.git/credentials"
 echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
+echo
 
-exit 0
+git checkout "${BUILD_SOURCEBRANCHNAME}"
+CANDIDATE=$(echo ${BUILD_SOURCEBRANCHNAME} | cut -c 8-)
+if [[ -z $CANDIDATE ]]; then
+  echo Could not determine dataset candidate to update
+  exit 1
+fi
 
-if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
-  echo Installing github cli
-  pushd .. >/dev/null
-  wget -nv https://github.com/github/hub/releases/download/v2.6.0/hub-linux-amd64-2.6.0.tgz -O - | tar xz || exit 1
-  export PATH=$(pwd)/hub-linux-amd64-2.6.0/bin/:${PATH}
-  popd >/dev/null
-  hub --version || exit 1
-
-  echo Open pull requests:
-  declare -A UPDATEBRANCHES
-  for BRANCH in $(hub pr list -b master -f '%H%n'); do
-    echo ${BRANCH}
-    UPDATEBRANCHES[${BRANCH}]=1
-  done
-  echo
-
-  echo Installing package outside tox environment
-  pip install -e .
-
-  echo Checking for required definition updates...
-  for DATASET in $(python -c "import dials_data.datasets as ddd; print('\n'.join(ddd.fileinfo_dirty))")
-  do
-    echo Checking ${DATASET}
-    [ ${UPDATEBRANCHES[update-${DATASET}]+x} ] || {
-      echo create/update branch ${DATASET}
-      git checkout -b "update-${DATASET}"
-      git reset --hard master
-      git commit --allow-empty -m "Trigger update of dataset ${DATASET}"
-      git push -f -u origin "update-${DATASET}"
-      echo create pull request
-      hub pull-request -f -m "Update dataset ${DATASET}"
+echo "##[section]Considering updating information on dataset ${CANDIDATE}"
+for DATASET in $(dials.data list --quiet --missing-hashinfo)
+do
+  if [[ "${DATASET}" == "${CANDIDATE}" ]]; then
+    echo "##[section]Updating dataset ${DATASET}"
+    dials.data get --create-hashinfo ${DATASET}
+    mv ${DATASET}.yml dials_data/hashinfo/${DATASET}.yml
+    if [ -z "$(git status --porcelain)" ]; then
+      echo Working directory remained clean. Something went wrong.
+      exit 1
+    fi
+    git add dials_data/hashinfo/${DATASET}.yml
+    echo
+    echo "##[section]Committing update"
+    git commit -m "Update file information for dataset ${DATASET}"
+    # Ensure dataset will not be downloaded again in the next round
+    dials.data list --quiet --missing-hashinfo | tee remaining-datasets
+    grep -- "^${DATASET}$" < remaining-datasets && {
+      echo Hashinfo sanity check failed
+      exit 1
     }
-  done
-fi
-
-if [[ ${TRAVIS_BRANCH} == update-* ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
-  git checkout "${TRAVIS_BRANCH}"
-  CANDIDATE=$(echo ${TRAVIS_BRANCH} | cut -c 8-)
-  if [[ ! -z $CANDIDATE ]]; then
-    echo Installing package outside tox environment
-    pip install -e .
-
-    echo Considering updating information on dataset ${CANDIDATE}
-    for DATASET in $(dials.data list --quiet --missing-hashinfo)
-    do
-      if [[ "${DATASET}" == "${CANDIDATE}" ]]; then
-        echo Updating dataset ${DATASET}
-        dials.data get --create-hashinfo ${DATASET} || exit 1
-        mv ${DATASET}.yml dials_data/hashinfo/${DATASET}.yml || exit 1
-        if [ -z "$(git status --porcelain)" ]; then
-          echo Working directory remained clean. Something went wrong.
-          exit 1
-        fi
-        git add dials_data/hashinfo/${DATASET}.yml || exit 1
-        echo Committing update
-        git commit -m "Update file information for dataset ${DATASET}" || exit 1
-        # Ensure dataset will not be downloaded again in the next round
-        dials.data list --quiet --missing-hashinfo | tee remaining-datasets || exit 1
-        grep -- "^${DATASET}$" < remaining-datasets && {
-          echo Hashinfo sanity check failed
-          exit 1
-        }
-        git push || exit 1
-        echo Success.
-        break
-      fi
-    done
+    git push
+    echo Success.
+    exit 0
   fi
-fi
+done
+
+echo "##[error]Could not identify candidate to update. Something went wrong"
+exit 1
